### ISSUE TITLE
Lighthouse Issue

### ISSUE THREAD

**Issue by Locis1** [ausi/respimagelint#95] opened 2024-11-06 21:37 UTC
I don't know if I'm doing something wrong, but even though the RspImageLinter says everything fits, Lighthouse still criticizes it.
![image](https://github.com/user-attachments/assets/b52cc546-440e-47c9-bc43-abcfa7ab796b)
![image](https://github.com/user-attachments/assets/185055b8-822d-47b5-9377-46b818c77db9)

**Comment by ausi** [comment] 2024-11-07 11:16
Can you post a screenshot of the whole lighthouse report or link to it? 
From the screenshot it appears that it thinks the compression is too low, or is it explicitly complaining about the dimensions of the resources?

**Comment by Locis1** [comment] 2024-11-07 11:40
Sure, of course!
Here is the link to the Lighthouse report: [Lighthouse Report](https://pagespeed.web.dev/analysis/https-drorian-dorian-baumann-de/lab8n5lilk?form_factor=mobile)
And here is the link to the website, in case it's needed as well: [Website](https://drorian.dorian-baumann.de/)

**Comment by ausi** [comment] 2024-11-07 11:50
Looks like this is a duplicate of https://github.com/ausi/respimagelint/issues/70
To make Lighthouse happy you needed to optimize your images for a screen width of `360` (with `@2x` I think)
But it looks like this has changed since then to `412@​1.75` now: https://github.com/GoogleChrome/lighthouse/blob/92ec8cd9be798a6caf1b6ee2925bfee61690e924/third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts#L72-L73

**Comment by Locis1** [comment] 2024-11-07 11:58
Can you guide me on how exactly I can implement this change? Specifically, I’m unsure of how to adjust the image sizes and implement srcset to ensure the images are correctly optimized for the new screen width and resolution.

Would really appreciate any detailed steps or examples you can provide!

Thanks in advance!

**Comment by ausi** [comment] 2024-11-07 13:33
> Can you guide me on how exactly I can implement this change? 

For the first image mentioned in the report (IMG_1676) you should add a `648w` variant in the `srcset` of the image _(360px * 90vw * @2x = 648w)_

After that change run the lighthouse report again and check if the error goes away.

But instead of (micro-)optimizing for lighthouse it would be better to optimize for the viewport size that is most common to the actual visitors of the website.

**Comment by Locis1** [comment] 2024-11-07 15:55
First of all, thank you for your help. Unfortunately, I won't be able to test whether it works until later.

I tried to understand how you came up with the values so that I can solve it myself in the future. If I understand correctly, you're starting with the old phone display with a width of 360px, and Google uses 412px. Since you're calculating with @2 and Google uses @1.75, both of you arrive at the same result.

Since I have the same issue on the PC, would I also need to use the average value, meaning 1920px * 492px (the sizes I have), and @1?

Or are there other values I should use?

You also mentioned that I should avoid micro-optimizing for Lighthouse and instead focus on optimizing for the viewport size that is most common for the actual visitors of the website. Could you clarify how exactly to do that, and which values would apply?

Thanks in advance for your help!

**Comment by Locis1** [comment] 2024-11-07 20:59
I tried what you suggested, but I'm still seeing the same result. I'm not sure if I did something wrong, but I believe I followed your instructions correctly.

Here’s the code snippet I'm using:

html
Code kopieren
<img 
    src="./images/IMG_1676.webp" 
    srcset="
        ./images/IMG_1676-270x360.webp 270w,
        ./images/IMG_1676-492x656.webp 492w,
        ./images/IMG_1676-648x864.webp 648w,
        ./images/IMG_1676-780x1040.webp 780w,
        ./images/IMG_1676-984x1312.webp 984w,
        ./images/IMG_1676-1230x1640.webp 1230w,
        ./images/IMG_1676-1430x1907.webp 1430w,
        ./images/IMG_1676-1610x2147.webp 1610w,
        ./images/IMG_1676-1770x2360.webp 1770w,
        ./images/IMG_1676-1910x2547.webp 1910w,
        ./images/IMG_1676-2048x2731.webp 2048w" 
    sizes="(min-width: 1160px) 492px, 90vw" 
    fetchPriority="low" 
/>
Let me know if you see any issues with this setup or if there's another approach I should try. 
![image](https://github.com/user-attachments/assets/dc503233-fb44-4275-883b-0cd31e58a6b7)

**Comment by gitlabisbetterthangithub** [comment] 2024-11-18 05:22
> You also mentioned that I should avoid micro-optimizing for Lighthouse and instead focus on optimizing for the viewport size that is most common for the actual visitors of the website. Could you clarify how exactly to do that, and which values would apply?

You've got 11 different sizes for your srcset. A good rule of thumb is to only have 4 - 5 sizes, otherwise you end up with more image sizes for very little benefit.

Have a read of this article, it has a fantastic explanation on what image sizes you should cater for.
https://cloudfour.com/thinks/responsive-images-the-simple-way/#what-image-sizes-should-i-provide

**Comment by ausi** [comment] 2024-11-20 13:39
> If I understand correctly, you're starting with the old phone display with a width of 360px, and Google uses 412px. Since you're calculating with `@2` and Google uses `@1.75`, both of you arrive at the same result.

Yes, that is also my understanding that Google did test with `360@2x` in the past and now uses `412@1.75`. But I did not manually verify if that is actually the case.

> Since I have the same issue on the PC, would I also need to use the average value, meaning 1920px * 492px (the sizes I have), and `@1`?

No, your image uses `sizes="(min-width: 1160px) 492px, 90vw"` which means that the image is 492px wide on all desktop screens (that are 1160px or more wide). So for your desktop users you should provide one `492w` and one `984w` image, as most desktop users have a `@1x` oder `@2x` screen. RespImageLint (should) also suggest you to include these two exact widths.

> You also mentioned that I should avoid micro-optimizing for Lighthouse and instead focus on optimizing for the viewport size that is most common for the actual visitors of the website. Could you clarify how exactly to do that, and which values would apply?

If you have some analytics for your website you might be able to see screen sizes and pixel densities there. With these you can do the same calculations as we did for the Lighthouse case (`SCREEN_WIDTH * 90vw * PIXEL_DENSITY`) to get an optimal with for many of your users. But I would consider this also to be a micro-optimization that has only a small overall effect. The thing I wanted to get across is: don’t focus _too much_ on Lighthouse, your actual users might benefit more from your focus ☺️

> I tried what you suggested, but I'm still seeing the same result.

I need to investigate this in more detail I think. I’m not sure if I have the time for that in the near future though.

> but I initially trusted the Responsive Image Linter to provide the right srcset values so that Lighthouse would be happy and the websites I build would be more performant. However, it seems that Lighthouse calculates things differently than the Responsive Image Linter, and I’m not sure if @ausi is planning to change that or leave it as is.

My goal is, that the linter suggests optimizations that are beneficial for most use cases and help people improve performance. I will also try to make these suggestions fully compatible with Lighthouse. But what I like to avoid is to base the suggestions only on Lighthouse as this would be harmful to all the users that do not match with the device that Lighthouse currently uses for testing.

And, just for clarification: I think the current state of the linter is pretty good in this case, so future changes to the algorithm will probably only change very little.

**Comment by ausi** [comment] 2024-11-20 21:36
> > I tried what you suggested, but I'm still seeing the same result.
> 
> I need to investigate this in more detail I think. I’m not sure if I have the time for that in the near future though.

I tried this now by creating a test page that only uses the `IMG_1676` image: https://ausi.uber.space/respimagelint-issue-95.html
and Lighthouse is fine with it: 
![Bildschirmfoto 2024-11-20 um 22 27 00](https://github.com/user-attachments/assets/adec4707-c85b-4062-9af0-3325ea060bfb)
https://pagespeed.web.dev/analysis/https-ausi-uber-space-respimagelint-issue-95-html/929zm2zvbt?hl=en&form_factor=mobile

My guess why the image still shows up in your Lighthouse report is that there are other images on your page that it is not happy with, and that triggers all images with “potential” savings to get listed, and for that it uses a quality of `50` for WEBP which would result in the reported reduction of about 18.8 KB for `IMG_1676-648x864.webp`. This is just a wild guess from my side though.

**Comment by Locis1** [comment] 2024-11-21 09:30
> No, your image uses sizes="(min-width: 1160px) 492px, 90vw" which means that the image is 492px wide on all desktop screens (that are 1160px or more wide). So for your desktop users you should provide one 492w and one 984w image, as most desktop users have a @1x oder @2x screen. RespImageLint (should) also suggest you to include these two exact widths.

Thank you for your explanation. I'll try this out today.

> If you have some analytics for your website you might be able to see screen sizes and pixel densities there. With these you can do the same calculations as we did for the Lighthouse case (SCREEN_WIDTH * 90vw * PIXEL_DENSITY) to get an optimal with for many of your users. But I would consider this also to be a micro-optimization that has only a small overall effect. The thing I wanted to get across is: don’t focus too much on Lighthouse, your actual users might benefit more from your focus ☺️

Yes, actually, as you said, I don’t want to micro-optimize my websites just to satisfy Lighthouse. But unfortunately, my clients sometimes put too much emphasis on it.

> > My guess why the image still shows up in your Lighthouse report is that there are other images on your page that it is not happy with, and that triggers all images with “potential” savings to get listed, and for that it uses a quality of 50 for WEBP which would result in the reported reduction of about 18.8 KB for IMG_1676-648x864.webp. This is just a wild guess from my side though.
> 
> My guess why the image still shows up in your Lighthouse report is that there are other images on your page that it is not happy with, and that triggers all images with “potential” savings to get listed, and for that it uses a quality of 50 for WEBP which would result in the reported reduction of about 18.8 KB for IMG_1676-648x864.webp. This is just a wild guess from my side though.

But I think the guess isn't so far off. It could be the case, so I’ll try this out as well.



Danke dir nochmal für die Hilfe! Falls ich mich irgendwie revanchieren kann, indem ich dir mal irgendwo helfe oder dir was abnehme, sag einfach Bescheid.

**Comment by ausi** [comment] 2024-11-22 14:28
I updated the code that generates the suggested sizes now in 258b4ddba7c17a968d0a49e1aeaa155402867f43 to consider very common screen resolutions including the one that Lighthouse currently uses. So if you use the sizes that RespImageLint suggests, the Lighthouse report should be green too.

However, the linter would still show all checks passed for your example because all images fullfill the requirement of being less than 0.75 megapixels apart from the optimal size. We cannot adapt the way how Lighhouse works here because we have to take all screen sizes into account. Also, the screen resolution of `412@1.75` does not seem to be that common actually, but it seems to be a very good fit for a „minimal“ size.

**Closed by ausi** 2024-11-22 14:28 UTC
