### ISSUE TITLE
Js Error (blank white page in result)

### ISSUE THREAD

**Issue by Habibpoor77** [ausi/respimagelint#88] opened 2023-08-30 06:31 UTC
Hi
I saw the old issue but I think that happened again
the error is 

Uncaught SyntaxError: "[object Object]" is not valid JSON
and
Uncaught SyntaxError: Unexpected token 'r', "respImageL"... is not valid JSON

responsive image linter Extension doesn't work too.
chrome version is 116.0.5845.111

**Comment by ausi** [comment] 2023-08-30 07:50
I was not able to reproduce that. Which version of the chrome-extension are you using? Does this happen for all websites?

**Comment by Habibpoor77** [comment] 2023-08-30 08:16
Yes. 
in all websites has same issue.
chrome-extension version is 1.1.0 (currently added it)

**Comment by shaheerhashim10** [comment] 2023-08-30 14:18
I am also having the same issue

![image](https://github.com/ausi/respimagelint/assets/18272121/c702de58-039a-4720-9210-818206e3195c)

**Comment by shaheerhashim10** [comment] 2023-08-30 14:19
I am also having the same issue

![image](https://github.com/ausi/respimagelint/assets/18272121/90c81ca7-4943-4b57-901f-b6503d3ba697)

**Comment by peter-neumann-dev** [comment] 2023-08-30 20:06
I also received this error in a report this week. I could not reproduce it with the same versions. With both the bookmarklet and the extension, everything worked as it should.

I have tested in Chrome without other plugins to avoid that other extensions will harm something.

The details of the report were:

Chrome Version 116.0.5845.110 (Official Build) (arm64)
Mac 13.4.1 (22F82)

Website: spacejelly.dev

**Comment by colbyfayock** [comment] 2023-08-31 01:34
Screenshot the above report is referring to

<img width="1701" alt="image" src="https://github.com/ausi/respimagelint/assets/1045274/7b008260-dc68-4007-8f83-507a741f0696">

I just went through all of my extensions and interestingly enough, Metamask is preventing it from working. Once disabled, it works for me

<img width="1722" alt="image" src="https://github.com/ausi/respimagelint/assets/1045274/4e2cf284-74f2-4ddd-84c6-eeaffb3d9d9f">

https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

**Comment by ausi** [comment] 2023-08-31 09:01
@Habibpoor77 and @shaheerhashim10 do you also have this “metamask” extension installed in your browser?

**Comment by shaheerhashim10** [comment] 2023-08-31 09:41
@ausi despite adding the recommended screen sizes in the next `Image` sizes prop, RespImageLint still shows those images as unoptimized. Any idea why that's happening?

**Comment by ausi** [comment] 2023-08-31 10:18
> RespImageLint still shows those images as unoptimized.

@shaheerhashim10 please open a new issue for that including a screeshot of the report and a link to the affected website.

> I tried it on a new Chrome profile that has no extensions installed and it worked fine.

Closing this issue then as this seems to be an issue of the “metamask” extension.

**Closed by ausi** 2023-08-31 10:18 UTC

**Comment by mxmzb** [comment] 2023-12-30 09:55
> Screenshot the above report is referring to
> 
> <img alt="image" width="1701" src="https://private-user-images.githubusercontent.com/1045274/264509087-7b008260-dc68-4007-8f83-507a741f0696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzA0MDksIm5iZiI6MTcwMzkzMDEwOSwicGF0aCI6Ii8xMDQ1Mjc0LzI2NDUwOTA4Ny03YjAwODI2MC1kYzY4LTQwMDctOGY4My01MDdhNzQxZjA2OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMDk1NTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ1M2IzZDhkMjVhZDU2Mjc4YjhlNTU0NGI3NTI5MTFlZmVkOGFjMGE5MGFkN2ViMjU3NjU0NmUxNGZjNGU0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M0jNiF6zqIBzkN-2X0LV6m9tMNDiRJBK0diUz6Ybt1Q">
> I just went through all of my extensions and interestingly enough, Metamask is preventing it from working. Once disabled, it works for me
> 
> <img alt="image" width="1722" src="https://private-user-images.githubusercontent.com/1045274/264509884-4e2cf284-74f2-4ddd-84c6-eeaffb3d9d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzA0MDksIm5iZiI6MTcwMzkzMDEwOSwicGF0aCI6Ii8xMDQ1Mjc0LzI2NDUwOTg4NC00ZTJjZjI4NC03NGYyLTRkZGQtODRjNi1lZWFmZmIzZDlkOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMDk1NTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTMzOGZlOWYyYjI2NjRlNDgxZDY3NDE3YmI2MWM0N2I3N2RjNTE5YzBlNmNhYWU2MjNmMjcwN2M0NmFiY2I0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yRU2K7SN3WETx2v76AiD93tGRirhTCPeWGMvGrKTQBU">
> https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

Disabling Metamask / using a profile without metamask was the solution for me!
